void setup()
{
    Serial.begin(115200);
}

void loop()
{
    Serial.println("I'm calling, I'm calling");
    delay(1000);
    Serial.println("Calling on you to say");
    delay(1000);
    Serial.println("I want you, I want you");
    delay(1000);
    Serial.println("Maybe all night 'til day");
    delay(1000);
    Serial.println("I want you, I want you");
    delay(1000);
    Serial.println("Different towns to run to");
    delay(1000);
    Serial.println("Baby come to me, ha-ha-ha");
    delay(1000);
    Serial.println("Give it all to me");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa-pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa-pa-pa-pa-pa-pa-pa");
    delay(1000);
    Serial.println("Skibidi pa-pa");
    delay(1000);
    Serial.println("Skibidi boom-boom, ay");
    delay(1000);
    Serial.println("Skibidi boom-boom-boom-boom, ay");
    delay(1000);
    Serial.println("Skibidi boom-boom-boom-boom-boom-pa-pa-boom-boom");
    delay(1000);
    Serial.println("Skibidi pa-pa");
    delay(1000);
    Serial.println("Ay! Ay!");
    delay(1000);
    Serial.println("I'm falling, I'm falling");
    delay(1000);
    Serial.println("Waiting for you to say");
    delay(1000);
    Serial.println("I want you, I want you");
    delay(1000);
    Serial.println("Maybe like horse last hey");
    delay(1000);
    Serial.println("I want you, I want you");
    delay(1000);
    Serial.println("Together like one two");
    delay(1000);
    Serial.println("Baby come to me, right now");
    delay(1000);
    Serial.println("Now giving talk to me");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa-pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa-pa-pa-pa-pa-pa-pa");
    delay(1000);
    Serial.println("Skibidi pa-pa");
    delay(1000);
    Serial.println("Skibidi boom-boom, ay");
    delay(1000);
    Serial.println("Skibidi boom-boom-boom-boom, ay");
    delay(1000);
    Serial.println("Skibidi boom-boom-boom-boom-boom-pa-pa-boom-boom");
    delay(1000);
    Serial.println("Skibidi pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa-pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa-pa-pa-pa-pa-pa-pa");
    delay(1000);
    Serial.println("Skibidi pa-pa");
    delay(1000);
    Serial.println("Skibidi boom-boom, ay");
    delay(1000);
    Serial.println("Skibidi boom-boom-boom-boom, ay");
    delay(1000);
    Serial.println("Skibidi boom-boom-boom-boom-boom-pa-pa-boom-boom");
    delay(1000);
    Serial.println("Skibidi pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa-pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa-pa-pa-pa-pa-pa-pa");
    delay(1000);
    Serial.println("Skibidi pa-pa");
    delay(1000);
    Serial.println("Skibidi boom-boom, ay");
    delay(1000);
    Serial.println("Skibidi boom-boom-boom-boom, ay");
    delay(1000);
    Serial.println("Skibidi boom-boom-boom-boom-boom-pa-pa-boom-boom");
    delay(1000);
    Serial.println("Skibidi pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa-pa-pa");
    delay(1000);
    Serial.println("Skibidi wap-pa-pa-pa-pa-pa-pa-pa-pa");
    delay(1000);
    Serial.println("Skibidi pa-pa");
    delay(1000);
    Serial.println("Skibidi boom-boom, ay");
    delay(1000);
    Serial.println("Skibidi boom-boom-boom-boom, ay");
    delay(1000);
    Serial.println("Skibidi boom-boom-boom-boom-boom-pa-pa-boom-boom");
    delay(1000);
    Serial.println("Skibidi");
    delay(1000);
}
